import React, { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowUpRight, BookOpen, ChevronRight, Clock3, Database, ExternalLink, FileText, Link2, Network, Search, ShieldCheck, Sparkles, X } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { SEO } from '../components/SEO'

export type EstateModule = { id: number; name: string; slug: string }

export const ESTATE_MODULES: EstateModule[] = [
  ['Identity & Access','identity'], ['Portfolio','portfolio'], ['Properties','properties'], ['CRM & Lead Lifecycle','crm'], ['Deals & Contracts','deals'],
  ['Property Management','property-management'], ['Leasing','leasing'], ['Escrow & Payments','escrow'], ['Data & Market Intelligence','market-intel'], ['Acquisitions','acquisitions'],
  ['Demand Generation','marketing'], ['Transactions','transactions'], ['Finance','finance'], ['Insurance','insurance'], ['Field Operations','field'],
  ['Maintenance','maintenance'], ['Documents','documents'], ['Compliance','compliance'], ['Risk','risk'], ['Telemetry & IoT','telemetry'],
  ['ESG & GRESB','esg'], ['Capital Table & DLT','capital-table'], ['Governance','governance'], ['PredictiveLife','predictive-life'], ['Real Estate OS','real-estate-os'],
].map(([name, slug], i) => ({ id: i + 1, name, slug }))

const ENTITY = {
  id: 'DE-BER-091', name: 'Riverside Apartments', type: 'Apartment complex', location: 'Berlin, Germany', units: 48,
  occupancy: '94.2%', noi: '$42.8k / month', gresb: '88 / 100', tokenized: '25%', status: 'LIVE', lastVerified: '24 August 2026',
}

const EVIDENCE: Record<number, { title: string; source: string; record: string; confidence: string; statement: string }> = {
  1: { title: 'Payment Velocity Trend', source: 'Event Sourcing Ledger', record: 'evt_8f4b2c', confidence: '98.4%', statement: 'Rent payment on-time rate increased by 3.2% year over year.' },
  2: { title: 'Market Cap-Rate Analysis', source: 'Module 09 · Market Intelligence', record: 'mkt_ber_2026_q1', confidence: '94.1%', statement: 'Berlin commercial properties are averaging approximately 4.8% cap rate.' },
  3: { title: 'Tenant Risk Score Delta', source: 'Module 04 · CRM', record: 'risk_9a12', confidence: '91.8%', statement: 'The tenant risk score increased from 0.62 to 0.78.' },
}

function StatusBadge({ children = 'LIVE', ai = false }: { children?: React.ReactNode; ai?: boolean }) {
  return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider ${ai ? 'border-violet-200 bg-violet-50 text-violet-700' : 'border-emerald-200 bg-emerald-50 text-emerald-700'}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{children}</span>
}

function Citation({ n, onClick }: { n: number; onClick: (n: number) => void }) {
  return <button onClick={() => onClick(n)} className="mx-0.5 inline-flex h-5 min-w-5 items-center justify-center rounded border border-blue-200 bg-blue-50 px-1 text-[10px] font-bold text-blue-700 hover:bg-blue-100">{n}</button>
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return <h2 className="mb-4 mt-10 scroll-mt-24 border-b border-slate-200 pb-2 text-2xl font-normal text-slate-950">{children}</h2>
}

function Infobox({ navigateModule }: { navigateModule: (id: number) => void }) {
  const rows = [['Registry ID', ENTITY.id], ['Type', ENTITY.type], ['Location', ENTITY.location], ['Units', ENTITY.units], ['Occupancy', ENTITY.occupancy], ['Monthly NOI', ENTITY.noi], ['GRESB', ENTITY.gresb], ['Tokenized', ENTITY.tokenized]]
  return <aside className="rounded-sm border border-slate-300 bg-white shadow-sm">
    <div className="border-b border-slate-300 bg-slate-50 px-4 py-3"><div className="text-[10px] font-bold uppercase tracking-widest text-slate-500">Property</div><div className="mt-1 text-lg font-bold">{ENTITY.name}</div></div>
    <div className="border-b border-slate-200 px-4 py-3"><StatusBadge /></div>
    <dl className="divide-y divide-slate-200 text-sm">{rows.map(([label, value]) => <div key={label} className="grid grid-cols-[42%_58%] gap-2 px-4 py-2.5"><dt className="text-slate-500">{label}</dt><dd className={`text-right ${label === 'Registry ID' ? 'font-mono text-[11px]' : 'font-semibold text-slate-800'}`}>{value}</dd></div>)}</dl>
    <div className="border-t border-slate-200 px-4 py-3"><div className="mb-2 text-[10px] font-bold uppercase tracking-widest text-slate-500">Connected modules</div><div className="space-y-1">{[6,9,20,21,22,24,25].map(id => { const m = ESTATE_MODULES[id - 1]; return <button key={id} onClick={() => navigateModule(id)} className="flex w-full items-center justify-between rounded px-2 py-1.5 text-left text-xs text-blue-700 hover:bg-blue-50"><span>M{id.toString().padStart(2,'0')} · {m.name}</span><ArrowUpRight className="h-3.5 w-3.5" /></button> })}</div></div>
    <div className="border-t border-slate-200 px-4 py-3 text-[11px] text-slate-500">Last verified {ENTITY.lastVerified}</div>
  </aside>
}

function CommandPalette({ open, onClose, navigateModule }: { open: boolean; onClose: () => void; navigateModule: (id: number) => void }) {
  const [query, setQuery] = useState(''); const [selected, setSelected] = useState(0); const input = useRef<HTMLInputElement>(null)
  const commands = useMemo(() => {
    const q = query.toLowerCase().trim(); const base = [{ label: 'Open Riverside Apartments', desc: 'Canonical property record', module: 3, icon: BookOpen }, ...[6,9,20,21,22,24,25].map(id => ({ label: `Open ${ESTATE_MODULES[id-1].name}`, desc: `Module ${id.toString().padStart(2,'0')}`, module: id, icon: id === 24 ? Sparkles : Network }))]
    return q ? base.filter(x => `${x.label} ${x.desc}`.toLowerCase().includes(q)) : base
  }, [query])
  useEffect(() => { if (open) { setQuery(''); setSelected(0); requestAnimationFrame(() => input.current?.focus()) } }, [open])
  useEffect(() => { if (!open) return; const key = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose(); if (e.key === 'ArrowDown') { e.preventDefault(); setSelected(i => commands.length ? (i+1)%commands.length : 0) } if (e.key === 'ArrowUp') { e.preventDefault(); setSelected(i => commands.length ? (i-1+commands.length)%commands.length : 0) } if (e.key === 'Enter' && commands[selected]) { navigateModule(commands[selected].module); onClose() } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [open, commands, selected, onClose, navigateModule])
  if (!open) return null
  return <div className="fixed inset-0 z-[200]"><button aria-label="Close search" onClick={onClose} className="absolute inset-0 bg-slate-950/40 backdrop-blur-sm"/><div className="relative mx-auto mt-[12vh] w-[min(680px,calc(100vw-32px))] overflow-hidden rounded-lg border border-slate-300 bg-white shadow-2xl"><div className="flex items-center gap-3 border-b border-slate-200 px-4 py-4"><Search className="h-5 w-5 text-blue-600"/><input ref={input} value={query} onChange={e => { setQuery(e.target.value); setSelected(0) }} placeholder="Search Estate OS…" className="flex-1 bg-transparent text-base outline-none placeholder:text-slate-400"/><kbd className="rounded border border-slate-200 bg-slate-50 px-2 py-1 text-[9px]">ESC</kbd></div><div className="max-h-[440px] overflow-y-auto p-2">{commands.map((c,i) => { const Icon=c.icon; return <button key={c.label} onClick={() => { navigateModule(c.module); onClose() }} className={`flex w-full items-center gap-3 rounded-md px-3 py-3 text-left ${i===selected?'bg-blue-50':'hover:bg-slate-50'}`}><Icon className="h-5 w-5 text-blue-600"/><div className="flex-1"><div className="text-sm font-semibold">{c.label}</div><div className="text-xs text-slate-500">{c.desc}</div></div><ChevronRight className="h-4 w-4 text-slate-300"/></button> })}</div><div className="border-t border-slate-200 bg-slate-50 px-4 py-2 text-[10px] text-slate-500">↑↓ Navigate · Enter Open · Esc Close · / Search</div></div></div>
}

function ProvenanceDrawer({ citation, onClose }: { citation: number | null; onClose: () => void }) {
  if (!citation || !EVIDENCE[citation]) return null; const item=EVIDENCE[citation]
  return <div className="fixed inset-y-0 right-0 z-[210] w-[min(460px,100vw)] border-l border-slate-300 bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-200 p-5"><div><div className="text-[10px] font-bold uppercase tracking-widest text-violet-600">Evidence record</div><h2 className="mt-1 text-xl font-bold">{item.title}</h2></div><button onClick={onClose} className="rounded p-2 hover:bg-slate-100"><X className="h-5 w-5"/></button></div><div className="space-y-6 overflow-y-auto p-5"><div className="rounded border border-violet-200 bg-violet-50 p-4"><div className="flex items-center gap-2 text-xs font-bold text-violet-800"><Sparkles className="h-4 w-4"/>AI-derived evidence</div><p className="mt-3 text-sm leading-6 text-slate-700">{item.statement}</p></div><div><div className="mb-2 text-[10px] font-bold uppercase tracking-widest text-slate-400">Source lineage</div><div className="rounded border border-slate-200">{[['Source',item.source],['Record ID',item.record],['Confidence',item.confidence],['Timestamp','24 August 2026']].map(([a,b])=><div key={a} className="grid grid-cols-[100px_1fr] gap-3 border-b border-slate-100 p-3 last:border-0"><span className="text-xs text-slate-400">{a}</span><span className="text-right text-xs text-slate-700">{b}</span></div>)}</div></div><div><div className="mb-2 text-[10px] font-bold uppercase tracking-widest text-slate-400">Evidence chain</div>{['Raw event','Normalized event','Derived metric','AI interpretation'].map((s,i)=><div key={s} className="mb-2 flex items-center gap-3 rounded border border-slate-200 p-3"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-slate-100 text-[10px] font-bold">{i+1}</span><span className="text-sm">{s}</span>{i<3&&<ChevronRight className="ml-auto h-4 w-4 text-slate-300"/>}</div>)}</div></div></div>
}

export default function EstateEncyclopedia() {
  const navigate = useNavigate(); const [params] = useSearchParams(); const [commandOpen,setCommandOpen]=useState(false); const [citation,setCitation]=useState<number|null>(null); const [peek,setPeek]=useState(false)
  const navigateModule = (id:number) => { const m=ESTATE_MODULES[id-1]; if (m) navigate(`/realestate-os?module=${m.slug}&entity=${ENTITY.id}`) }
  useEffect(() => { const key=(e:KeyboardEvent) => { if ((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k') { e.preventDefault(); setCommandOpen(true) } if (e.key==='/' && !(e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement)) { e.preventDefault(); setCommandOpen(true) } }; window.addEventListener('keydown',key); return()=>window.removeEventListener('keydown',key) }, [])
  const jump=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'})
  return <div className="min-h-screen bg-white text-slate-900"><SEO title={`${ENTITY.name} · Estate OS Encyclopedia`} description="Canonical Estate OS property knowledge record."/><header className="sticky top-0 z-50 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex h-14 max-w-[1500px] items-center gap-5 px-5"><button onClick={()=>navigate('/')} className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded bg-blue-700 text-xs font-black text-white">EO</span><span className="text-sm font-black tracking-tight">ESTATE OS</span></button><button onClick={()=>setCommandOpen(true)} className="ml-auto flex w-[min(460px,55vw)] items-center gap-2 rounded-md border border-slate-300 bg-slate-50 px-3 py-2 text-left text-xs text-slate-400 hover:border-blue-300"><Search className="h-4 w-4"/>Search the encyclopedia<kbd className="ml-auto rounded border bg-white px-1.5 py-0.5 text-[9px]">⌘K</kbd></button><StatusBadge>Knowledge graph online</StatusBadge></div></header>
    <div className="border-b border-slate-200"><div className="mx-auto flex max-w-[1500px] flex-wrap items-center gap-2 px-5 py-3 text-xs text-slate-500"><button onClick={()=>navigate('/realestate-os')} className="text-blue-700 hover:underline">Real Estate OS</button><ChevronRight className="h-3 w-3"/><span>Properties</span><ChevronRight className="h-3 w-3"/><span>Germany</span><ChevronRight className="h-3 w-3"/><span>Berlin</span><ChevronRight className="h-3 w-3"/><strong>{ENTITY.name}</strong></div></div>
    <main className="mx-auto max-w-[1500px] px-5 py-8"><div className="mb-8 border-b border-slate-300 pb-7"><div className="mb-3 flex flex-wrap items-center gap-2"><StatusBadge/><span className="font-mono text-[11px] text-slate-500">{ENTITY.id}</span><span className="text-slate-300">•</span><span className="text-xs text-slate-500">{ENTITY.type}</span></div><h1 className="text-4xl font-normal tracking-tight md:text-5xl">{ENTITY.name}</h1><p className="mt-3 max-w-4xl text-base leading-7 text-slate-600">Riverside Apartments is a registered residential property entity in Berlin. Estate OS connects its ownership, tenancy, financial, operational, environmental, capital and predictive records into one canonical knowledge surface.</p><div className="mt-5 flex flex-wrap items-center gap-2"><button onClick={()=>setPeek(true)} className="inline-flex items-center gap-1 rounded border border-blue-200 bg-blue-50 px-3 py-1.5 text-xs font-semibold text-blue-700"><BookOpen className="h-3.5 w-3.5"/>Entity preview</button><button onClick={()=>navigateModule(25)} className="inline-flex items-center gap-1 rounded border border-slate-300 px-3 py-1.5 text-xs text-slate-600">Open in Real Estate OS <ExternalLink className="h-3.5 w-3.5"/></button><span className="ml-auto flex items-center gap-1 text-[11px] text-slate-400"><Clock3 className="h-3.5 w-3.5"/>Verified {ENTITY.lastVerified}</span></div></div>
      <div className="flex gap-8"><nav className="sticky top-20 hidden w-48 shrink-0 self-start xl:block"><div className="border-l border-slate-200 pl-4"><div className="mb-3 text-[10px] font-bold uppercase tracking-widest text-slate-400">Contents</div>{[['overview','Overview'],['ownership','Ownership'],['financials','Financials'],['tenancy','Tenancy'],['operations','Operations'],['esg','ESG & Sustainability'],['predictive','Predictive Intelligence'],['provenance','Provenance'],['related','Related entities']].map(([id,label])=><button key={id} onClick={()=>jump(id)} className="block w-full border-l-2 border-transparent py-1 pl-3 text-left text-xs text-slate-500 hover:border-blue-600 hover:text-blue-700">{label}</button>)}</div></nav>
        <article className="min-w-0 max-w-3xl flex-1"><section id="overview"><SectionTitle>Overview</SectionTitle><p className="leading-7 text-slate-700">Riverside Apartments contains 48 residential units with current occupancy of {ENTITY.occupancy}. Operational metrics are live state, while descriptive article content remains a stable knowledge record.</p><div className="my-6 grid grid-cols-2 gap-px overflow-hidden rounded border border-slate-200 bg-slate-200 sm:grid-cols-4">{[['Units',ENTITY.units],['Occupancy',ENTITY.occupancy],['NOI',ENTITY.noi],['GRESB',ENTITY.gresb]].map(([a,b])=><div key={a} className="bg-white p-4"><div className="text-[10px] font-bold uppercase tracking-widest text-slate-400">{a}</div><div className="mt-1 text-lg font-bold">{b}</div></div>)}</div></section>
          <section id="ownership"><SectionTitle>Ownership</SectionTitle><p className="leading-7 text-slate-700">Ownership is represented as a connected entity, allowing beneficial interests and capital positions to be resolved without duplicating the property record.</p><EntityLink name="Riverside Holdings" type="Capital Table · Module 22" onClick={()=>navigateModule(22)}/></section>
          <section id="financials"><SectionTitle>Financials</SectionTitle><p className="leading-7 text-slate-700">Current monthly NOI is {ENTITY.noi}. Financial state is operational data and can change independently from historical article revisions.<Citation n={1} onClick={setCitation}/><Citation n={2} onClick={setCitation}/></p><Notice><Database className="h-4 w-4"/>Operational values are dynamic and should always be evaluated against their latest verification timestamp.</Notice></section>
          <section id="tenancy"><SectionTitle>Tenancy</SectionTitle><p className="leading-7 text-slate-700">Occupancy is currently {ENTITY.occupancy}. Tenant records, leases, payment velocity and lifecycle events remain linked to CRM and leasing domains.<Citation n={3} onClick={setCitation}/></p><EntityLink name="Property Management" type="Module 06" onClick={()=>navigateModule(6)}/></section>
          <section id="operations"><SectionTitle>Operations</SectionTitle><p className="leading-7 text-slate-700">Field inspections, maintenance records and telemetry enrich the property entity continuously.</p><div className="grid gap-2 sm:grid-cols-2"><EntityLink name="Riverside IoT Network" type="Telemetry · Module 20" onClick={()=>navigateModule(20)}/><EntityLink name="Field Operations" type="Module 15" onClick={()=>navigateModule(15)}/></div></section>
          <section id="esg"><SectionTitle>ESG & Sustainability</SectionTitle><p className="leading-7 text-slate-700">The current GRESB score is <strong>{ENTITY.gresb}</strong>. ESG state connects building telemetry, energy information and sustainability reporting.</p><EntityLink name="ESG & GRESB" type="Module 21" onClick={()=>navigateModule(21)}/></section>
          <section id="predictive"><SectionTitle>Predictive Intelligence</SectionTitle><Notice ai><Sparkles className="h-4 w-4"/>AI-generated insight</Notice><p className="leading-7 text-slate-700">PredictiveLife can combine tenancy, operational, financial and market signals into forward-looking property intelligence.<Citation n={1} onClick={setCitation}/></p><button onClick={()=>navigateModule(24)} className="mt-3 inline-flex items-center gap-2 rounded border border-violet-200 bg-violet-50 px-3 py-2 text-xs font-semibold text-violet-700"><Sparkles className="h-4 w-4"/>Open PredictiveLife</button></section>
          <section id="provenance"><SectionTitle>Provenance</SectionTitle><p className="leading-7 text-slate-700">Estate OS distinguishes canonical metadata, operational records and AI-derived conclusions. Every AI assertion should expose its evidence lineage.</p><div className="my-5 space-y-2">{[1,2,3].map(n=><button key={n} onClick={()=>setCitation(n)} className="flex w-full items-center gap-3 rounded border border-slate-200 p-3 text-left hover:border-blue-300 hover:bg-blue-50"><FileText className="h-4 w-4 text-blue-600"/><span className="flex-1 text-xs font-medium">Evidence record {n} · {EVIDENCE[n].title}</span><ArrowUpRight className="h-4 w-4 text-slate-400"/></button>)}</div></section>
          <section id="related"><SectionTitle>Related entities</SectionTitle>{[['Property Management',6],['Market Intelligence',9],['Telemetry',20],['ESG & GRESB',21],['Capital Table & DLT',22],['PredictiveLife',24],['Real Estate OS',25]].map(([name,id])=><EntityLink key={String(id)} name={String(name)} type={`Module ${String(id).padStart(2,'0')}`} onClick={()=>navigateModule(Number(id))}/>)}</section>
          <section className="mt-14 border-t border-slate-300 pt-7"><h2 className="text-xl font-bold">References</h2><ol className="mt-4 space-y-3 text-xs text-slate-600"><li><strong>[1]</strong> Event Sourcing Ledger · payment velocity records.</li><li><strong>[2]</strong> Module 09 · Data & Market Intelligence.</li><li><strong>[3]</strong> Module 04 · CRM & Lead Lifecycle.</li></ol></section><footer className="mt-10 border-t border-slate-200 py-6 text-[11px] leading-5 text-slate-500">Estate OS Encyclopedia · Canonical knowledge surface · Dynamic operational values are explicitly distinguished from historical article content.</footer></article>
        <div className="hidden w-72 shrink-0 lg:block"><Infobox navigateModule={navigateModule}/></div></div></main>
    {peek&&<div className="fixed bottom-5 right-5 z-[100] w-[min(420px,calc(100vw-32px))] overflow-hidden rounded-lg border border-slate-300 bg-white shadow-2xl"><div className="flex items-start justify-between border-b p-4"><div><div className="text-[10px] font-bold uppercase tracking-widest text-blue-600">Entity preview</div><h3 className="mt-1 text-lg font-bold">{ENTITY.name}</h3><p className="text-xs text-slate-500">{ENTITY.type} · {ENTITY.location}</p></div><button onClick={()=>setPeek(false)}><X className="h-4 w-4"/></button></div><div className="grid grid-cols-3 divide-x"><Mini label="Units" value={ENTITY.units}/><Mini label="Occupancy" value={ENTITY.occupancy}/><Mini label="GRESB" value={ENTITY.gresb}/></div><div className="border-t bg-slate-50 p-3"><div className="flex flex-wrap gap-2">{[6,21,22].map(id=><button key={id} onClick={()=>navigateModule(id)} className="rounded border border-slate-300 bg-white px-2 py-1 text-[11px] text-blue-700">{ESTATE_MODULES[id-1].name} ↗</button>)}</div></div></div>}
    <ProvenanceDrawer citation={citation} onClose={()=>setCitation(null)}/><CommandPalette open={commandOpen} onClose={()=>setCommandOpen(false)} navigateModule={navigateModule}/></div>
}

function EntityLink({ name, type, onClick }: { name: string; type: string; onClick: () => void }) { return <button onClick={onClick} className="my-3 flex w-full items-center gap-3 rounded border border-slate-200 bg-slate-50 p-3 text-left hover:border-blue-300 hover:bg-blue-50"><Link2 className="h-4 w-4 text-blue-600"/><div className="flex-1"><div className="text-sm font-semibold text-blue-700">{name}</div><div className="text-[11px] text-slate-500">{type}</div></div><ArrowUpRight className="h-4 w-4 text-slate-400"/></button> }
function Notice({ children, ai=false }: { children: React.ReactNode; ai?: boolean }) { return <div className={`my-5 flex items-start gap-3 rounded border p-3 text-xs ${ai?'border-violet-200 bg-violet-50 text-violet-800':'border-blue-200 bg-blue-50 text-blue-800'}`}>{children}</div> }
function Mini({ label, value }: { label: string; value: React.ReactNode }) { return <div className="p-3"><div className="text-[10px] uppercase tracking-wide text-slate-400">{label}</div><div className="mt-1 text-sm font-bold">{value}</div></div> }
